export const AUTH_DEFINITIONS = {
  SESSION_MAX_AGE_SECONDS: 60 * 60 * 24 * 7,
  SESSION_UPDATE_AGE_SECONDS: 60 * 60 * 24,
  INVITATION_MAX_AGE_SECONDS: 60 * 60 * 24 * 7,
  COOKIE_NAME: "kaine_session"
} as const;
