// Generated by scripts/sync-mobile-design-tokens.mjs. Do not edit.
export const nativeThemeTokens = {
  light: {
    background: "#f6f6f7",
    surface: "#ffffff",
    text: "#202124",
    subtle: "#61636a",
    border: "#dcdde1",
    primary: "#0c66e4",
    selected: "#e9f2ff"
  },
  dark: {
    background: "#17181a",
    surface: "#202124",
    text: "#eeeff1",
    subtle: "#b0b2b9",
    border: "#41444b",
    primary: "#579dff",
    selected: "#1c2b41"
  }
};

export const motionDurations = {
  control: 120,
  overlay: 180,
  drawer: 220
};
